spring:
  application:
    name: demo5work


  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/library_db
    username: admin_user
    password: DI-624+a

  # JPA 配置
  jpa:
    hibernate:
      ddl-auto: create-drop  # 每次启动时重新创建表（开发环境）
    show-sql: true  # 显示 SQL 语句
    properties:
      hibernate:
        format_sql: true  # 格式化 SQL
        use_sql_comments: true  # 显示注释
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false  # 避免懒加载问题

# 服务器端口
server:
  port: 8080

# 日志配置
logging:
  level:
    root: INFO
    com.example.jpaadvanceddemo: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
